### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by ghost** [cameronkinsella/manga-translator#8]
I tried following the 'steps' in the readme, but I dont know where to find the JSON.
does anyone have a better guide on how to set this up?

**Comment by cameronkinsella** [comment]
I'm sorry to hear that you've been having issues with the setup. I'm going to close this issue since I would need more information to help and it looks like you deleted your GitHub account. If you happen to see this and decide to create a new account, feel free to open another issue and I'll try to help resolve your problem.
